### ISSUE TITLE
Example of usage?

### ISSUE THREAD

**Issue by Vungo0510** [vivekmarakana/yii2-image-gallery-selector#1]
Hi Vivek,
Do you mind adding an example of how to use this widget? Or more precisely, what should I declare as the $images variable in this statement: 
\vivekmarakana\widgets\GallerySelector::widget(['images' => $images])?

I tried the following code in view and controller but it didn't work. My view file:
<img width="766" alt="screen shot 2016-05-24 at 3 32 30 pm" src="https://cloud.githubusercontent.com/assets/9064688/15495792/bdfbd462-21c4-11e6-9158-9957221e3b12.png">
My controller method:
<img width="645" alt="screen shot 2016-05-24 at 3 33 25 pm" src="https://cloud.githubusercontent.com/assets/9064688/15495825/e20eebaa-21c4-11e6-9e59-fdc928360e4c.png">
This is what I get currently when browsing the gallery:
<img width="1058" alt="screen shot 2016-05-24 at 3 34 41 pm" src="https://cloud.githubusercontent.com/assets/9064688/15495846/0d121eb2-21c5-11e6-8e6a-62a05754a8fe.png">
The number of images in the gallery is correct but all the images are displayed as gray boxes

**Comment by vivekmarakana** [comment]
Hi,

Each image object should look something like following:

``` php
foreach (Image::find()->each(100) as $row) {
    $image = [
        'name' => $row->image_name, //optional
        'url' => $row->url,
        'id' => 'image-' . $row->id,
    ];
}
```

**Comment by vivekmarakana** [comment]
I've also updated usage in README file.

**Comment by Vungo0510** [comment]
Thank you! I will try it out
